#!/usr/bin/env node
// Final numbers for the capture -> docs/capture-summary.md (and stdout).
import fs from 'node:fs';
import path from 'node:path';
import { PATHS, ROOT, SITE_ORIGIN } from './lib/config.mjs';
import { readJson, writeFile, mdTable, fmtBytes, listFiles } from './lib/util.mjs';

const inv = readJson(path.join(PATHS.work, 'inventory.json'));
const build = readJson(path.join(PATHS.work, 'build-report.json'));
const assets = readJson(path.join(PATHS.work, 'assets.json'), []);
const vd = readJson(path.join(PATHS.work, 'visual-diff-local.json'), []);
const lc = readJson(path.join(PATHS.work, 'link-check.json'), null);
const decisions = readJson(path.join(PATHS.work, 'page-source-decisions.json'), []);

const pages = inv.rows.filter((r) => r.type === 'page' && Number(r.http_status) === 200);
const okAssets = assets.filter((a) => a.status === 200);
const siteFiles = listFiles(PATHS.site);
const siteBytes = siteFiles.reduce((s, f) => s + fs.statSync(f).size, 0);
const shots = listFiles(path.join(PATHS.docs, 'screenshots', 'live'));
const vdPass = vd.filter((r) => r.pass).length;
const lfsCount = fs.existsSync(path.join(ROOT, '.gitattributes'))
  ? fs.readFileSync(path.join(ROOT, '.gitattributes'), 'utf8').split('\n').filter((l) => l && !l.startsWith('#') && !l.startsWith('*.')).length
  : 0;

const rows = [
  ['Site', SITE_ORIGIN],
  ['Captured', inv.generatedAt],
  ['Pages (HTTP 200 HTML)', pages.length],
  ['… of which not in any sitemap', pages.filter((r) => !r.source.includes('sitemap')).length],
  ['Inventory rows (pages, redirects, feeds, sitemaps, icons, 404 …)', inv.rows.length],
  ['Excluded URLs (admin/API, robots.txt, query variants, sub-sites)', inv.excluded.length],
  ['Sub-sites excluded', inv.subsites.map((s) => s.id).join(', ') || 'none'],
  ['Assets downloaded', `${okAssets.length} files, ${fmtBytes(okAssets.reduce((s, a) => s + a.bytes, 0))}`],
  ['Asset URLs that failed on the live site', assets.length - okAssets.length],
  ['site/ folder', `${siteFiles.length} files, ${fmtBytes(siteBytes)}`],
  ['Pages served from rendered DOM / as-delivered HTML', `${build.pagesFromRendered} / ${build.pages.length - build.pagesFromRendered}`],
  ['Live screenshots', shots.length],
  ['Visual diff pass rate (≤ 1% different)', vd.length ? `${vdPass}/${vd.length} (${((vdPass / vd.length) * 100).toFixed(1)}%)` : 'not run'],
  ['Requests from the copy to the live site', vd.reduce((s, r) => s + (r.leaks || 0), 0)],
  ['Unresolved internal references (fixable)', lc ? `${lc.missing.length} (${lc.fixable})` : 'not run'],
  ['Broken links, HTTP crawl (fixable)', lc ? `${lc.linkinator.uniqueBroken} (${lc.linkinator.brokenFixable})` : 'not run'],
  ['Inventory URLs with their file', lc ? `${lc.coverage.applicable - lc.coverage.missing}/${lc.coverage.applicable}` : 'not run'],
  ['Tracking services disabled', build.trackers.map((t) => `${t.name}${t.ids.length ? ` (${t.ids.join(', ')})` : ''}`).join('; ') || 'none'],
  ['Unique forms', build.forms],
  ['Redirects observed / in _redirects', `${build.redirects.total} / ${build.redirects.inNetlifyFile}`],
  ['Images > 1 MB stored with Git LFS', lfsCount],
  ['Politeness: network requests / peak concurrency', `${inv.fetchStats.network}+ / ${inv.fetchStats.peakSiteConcurrency}`],
];
const md = [
  '# Capture summary',
  '',
  'Generated by `scripts/07-summary.mjs` at the end of `scripts/capture-all.sh`.',
  '',
  mdTable(['', ''], rows),
  '',
  decisions.length
    ? '## Pages switched to the as-delivered HTML\n\n' +
      mdTable(['Page', 'Rendered DOM diff (worst viewport)', 'As-delivered diff', 'Used'], decisions.map((d) => [new URL(d.url).pathname, `${d.renderedWorstPct}%`, `${d.rawWorstPct}%`, d.chosen === 'raw' ? 'as-delivered' : 'rendered']))
    : '',
  '',
].join('\n');
writeFile(path.join(PATHS.docs, 'capture-summary.md'), md);
for (const [k, v] of rows) console.log(`${k}: ${v}`);
